### PR TITLE
allow custom divisor

### PR DESCRIPTION
**Pull request by liubiin**
Some UART, for example 8250_omap, has multiple Over Sampling modes. It
might have platform defined divisor parameter to choose the mode. So
this patch allow to directly pass in custom_divisor to kernel without
checking the speed.

Signed-off-by: Bin Liu <b-liu@ti.com>

### CODE REVIEW

**Comment by andy-shev** [comment]
I'm not sure we need to support this. If you need a good solution, use BOTHER from termios2. I think OMAP driver supports that already. If no, fix the driver -- it's 2020 year here.

**Comment by liubiin** [comment]
> Why not a positive conditional?
Not sure I understand your question, the new code has both if and else branches.

**Comment by liubiin** [comment]
> What the point of this change?

to pass in the command line parameter -d

**Comment by liubiin** [comment]
> I'm not sure we need to support this. If you need a good solution, use BOTHER from termios2. I think OMAP driver supports that already. If no, fix the driver -- it's 2020 year here.
> 
> JFYI: I plan to drop custom divisor support fro Linux kernel completely (in favour of BOTHER).

Ok, let me dig into BOTHER... Thanks.

**Comment by cbrake** [comment]
#17 and #22 may have some useful reference links for this issue.

**Comment by andy-shev** [comment]
> > Why not a positive conditional?
> > Not sure I understand your question, the new code has both if and else branches.

Easier to parse `if (foo) {} else {}` then `if (!bar) {} else {}` exactly by the reason that there are two branches are present.

**Comment by andy-shev** [comment]
> > What the point of this change?
> 
> to pass in the command line parameter -d

It's already there, what the difference and what the point of the change?

**Comment by liubiin** [comment]
> > > What the point of this change?
> > 
> > 
> > to pass in the command line parameter -d
> 
> It's already there, what the difference and what the point of the change?

The code only defines the cmdline option, but doesn't use its corresponding parameter. This patch adds the usage of it.

**Comment by andy-shev** [comment]
@liubiin
I don't see it. What I see is the (unnecessary) replacement of _atoi()_.

**Comment by liubiin** [comment]
What you don't see? _cl_divisor is defined but not used in the original code? or how _cl_divisor is passed into kernel in my patch? If former, please do 'git grep _cl_divisor'; if latter, can you see the 'else' branch is only one line in my patch - _cl_divisor is assigned to ss.custom_divisor?

**Comment by cbrake** [comment]
It appears I created the _cl_divisor command line option years ago, but then never actually implemented code to use it:

https://github.com/cbrake/linux-serial-test/commit/4efb8e880899ef88cb948cf846b528754b4b0592

Apparently the code that calculates `ss.custom_divisor` worked well enough for me at the time.

This change looks OK to me. It seems until someone has time to implement BOTHER support, this is reasonable. Additionally, I wonder if we should keep the custom divisor support for awhile yet to support older systems, that may not have BOTHER support in the kernel.

In addition to @liubiin 's changes, I would suggest the following tweaks:

https://github.com/cbrake/linux-serial-test/commit/08c29e4c1003bfeeff07f8a9ffcad787a0407d95

Implements @andy-shev 's suggestion on the if logic, and passes divisor to function instead of using global command line vars.

@liubiin can you test this change with your hardware and make sure the divisor command line option still works?

@andy-shev do you see any problems with this?

Thanks for all the input!

**Comment by cbrake** [comment]
@liubiin here is the branch that has my additional commit:

https://github.com/cbrake/linux-serial-test/tree/feature-custom-divisor

**Comment by liubiin** [comment]
@cbrake I just tested your new branch which has the cleanup, and it still works for me. I like the idea that don't use global vars in functions. Thanks for the cleanup.

**Comment by cbrake** [comment]
@liubiin thanks for testing.

**Comment by liubiin** [comment]
BTY, I am not quite sure the way to calculate ss.custom_divisor is correct in else() where _cl_divisor is not specified in cmdline:

ss.custom_divisor = (ss.baud_base + (speed/2)) / speed;

It seems ss.baud_base is 3000000 in my test, so this calculation only works if the UART clk is 48MHz and oversampling is 16x (3000000 x 16 = 48MHz). Does this formula still work if the UART clk is not 48MHz?

**Comment by cbrake** [comment]
@liubiin you are likely correct -- this code was perhaps used on an old PXA270 system (or may have been DM3730), and I have not used it since. I don't have time to sort through it right now, so with BOTHER coming on, I'd be inclined to just consider this "divisor calculation" legacy code, and if someone needs to set the divisor, your patch gives them a way to manually do this.

**Comment by liubiin** [comment]
Well, I just tested custom baud rates on a UART which clock is 192MHz, and the formula of calculating ss.custom_divisor works! Then I found in kernel serial core driver that ss.baud_base = uartclk / 16. So the formula is indeed correct.

**Comment by andy-shev** [comment]
> What you don't see? _cl_divisor is defined but not used in the original code? or how _cl_divisor is passed into kernel in my patch? If former, please do 'git grep _cl_divisor'; if latter, can you see the 'else' branch is only one line in my patch - _cl_divisor is assigned to ss.custom_divisor?

The problem you have is the last hunk in your code. It's unnecessary churn which replaces `atoi()` with `strtol()`. For what purpose?

**Comment by andy-shev** [comment]
> @andy-shev do you see any problems with this?

Nope.

My comment was to the unnecessary hunk in the patch. The main idea can be implemented as proposed, but better with your clean up.

**Comment by cbrake** [comment]
I suspect the strtol (over atoi) gives us the flexibility to accept hexadecimal #'s. If that is the purpose, seems like a reasonable change.

From `man strtol`:

```
    The string may begin with an arbitrary amount of white space (as deter‐
       mined by isspace(3)) followed by a single optional '+' or '-' sign.  If
       base  is zero or 16, the string may then include a "0x" or "0X" prefix,
       and the number will be read in base 16; otherwise, a zero base is taken
       as  10  (decimal) unless the next character is '0', in which case it is
       taken as 8 (octal).
```

**Comment by liubiin** [comment]
Yes, being able to hex format is the reason to replace atoi() with strtol(). 8250_omap driver uses BIT16 of the divisor to specify for 13x oversampling, so using hex is easier.

**Comment by andy-shev** [comment]
> Yes, being able to hex format is the reason to replace atoi() with strtol(). 8250_omap driver uses BIT16 of the divisor to specify for 13x oversampling, so using hex is easier.

This is okay, though not explained in the commit message, why do we need an extra (unused) variable for that?

**Comment by cbrake** [comment]
yeah, looks like that can be simplified a bit:

https://github.com/cbrake/linux-serial-test/commit/fc5aa2f41cb3bf47e591574dc8c5e09ef514024a

even cleaner now :-)

**Comment by liubiin** [comment]
> > Yes, being able to hex format is the reason to replace atoi() with strtol(). 8250_omap driver uses BIT16 of the divisor to specify for 13x oversampling, so using hex is easier.
> 
> This is okay, though not explained in the commit message.

agreed, it would be nice if it was explained in the commit message.

> But why do we need an extra (unused) variable for that?

Good catch, I copied it from the 'y' option param without thinking of whether it is needed or not...

**Pull request merged**
